version: '3.8'
services:

  #  Настройки для чата       ↓↓↓↓↓
  redis:
    image: redis:7-alpine
    container_name: shop_redis

    ports:
      - "6379:6379"
    #    ports:
    #      - "8080:8080"
    restart: unless-stopped
    #    command: redis-server --save 30 1 --loglevel warning
    command: redis-server --save 5 1 --loglevel warning

  #  Настройки для чата       ↑↑↑↑↑


  #  Настройки для SQL       ↓↓↓↓↓
  mysql:
    image: mysql:8.0
    container_name: shop_mysql
    environment:
      MYSQL_DATABASE: diplom_db_shop_db
      MYSQL_USER: diplomdb
      MYSQL_PASSWORD: diplomdb
      MYSQL_ROOT_PASSWORD: rootpassword # Пароль суперпользователя
    ports:
      - "3306:3306"
    volumes:
      #   файлы из папки выполнятся при создании контейнера
      - ./docker/sql:/docker-entrypoint-initdb.d
      # Сохранение физических данных БД (чтобы не пропали при перезапуске)
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
volumes:
  mysql_data:
  #  Настройки для SQL       ↑↑↑↑↑
